spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ""
            client-secret: ""
  application:
    name: "demo"
logging:
  level:
    org.springframework.security: DEBUG
